/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.xwiki.contrib.latex.pdf;

import java.util.List;

import org.xwiki.component.annotation.Role;
import org.xwiki.stability.Unstable;

/**
 * Configuration options for converting from LaTeX to PDF.
 *
 * @version $Id$
 * @since 1.10
 */
@Role
@Unstable
public interface LaTeX2PDFConfiguration
{
    /**
     * @return the docker image to use to perform the conversion (e.g. {@code blang/latex:ubuntu})
     */
    String getDockerImageName();

    /**
     * @return the commands to execute inside the docker container to perform the conversion
     *         (e.g. {@code pdflatex -shell-escape index.tex}). Note that {@code index.tex} is entry file for the
     *         conversion, as generated by the LaTeX export.
     */
    List<String> getDockerCommands();

    /**
     * @return true if the docker container must be removed once the conversion is done. It can be useful to leave it
     *         for debugging purposes.
     */
    boolean autoRemoveContainer();
}
